# Generated by Django 2.2.3 on 2019-07-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255, verbose_name='title')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('expire_date', models.DateTimeField(verbose_name='date expired')),
                ('task_state', models.BooleanField(verbose_name='has finished')),
                ('description', models.TextField(blank=True, null=True)),
                ('task_priority', models.IntegerField(verbose_name='priority')),
            ],
        ),
    ]
