# Generated by Django 2.2.3 on 2019-07-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190710_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='has finished'),
        ),
    ]
